# Generated by Django 3.1.7 on 2021-03-17 11:29

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=mptt.fields.TreeManyToManyField(related_name='books', to='Polls.Genre'),
        ),
    ]
