# Generated by Django 3.1.7 on 2021-03-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0002_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='level',
        ),
        migrations.RemoveField(
            model_name='book',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='book',
            name='tree_id',
        ),
    ]
