# Generated by Django 3.1.7 on 2021-03-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0005_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Genre',
        ),
    ]
